version: 2.1

jobs:
  unit_tests:
    docker:
      - image: circleci/openjdk:11  # Base image con OpenJDK 11
      - image: circleci/mysql:8.0  # Servicio de MySQL
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: calidad2024
          MYSQL_USER: root
          MYSQL_PASSWORD: 123456
    steps:
      - checkout  # Descarga el código fuente

      # Configurar Maven y dependencias
      - run:
          name: Install Maven
          command: sudo apt-get update && sudo apt-get install -y maven

      # Construir el proyecto y omitir pruebas específicas
      - run:
          name: Build the project
          command: mvn clean install -DskipTests

      # Ejecutar pruebas ignorando UserDAOTest y UserServiceTest
      - run:
          name: Run unit tests (excluding UserDAOTest and UserServiceTest)
          command: |
            mvn test -Dtest=!UserDAOTest,!UserServiceTest,com.mayab.quality.functional.CRUDSeleniumTest,com.mayab.quality.functional.SeleniumTest

workflows:
  version: 2
  build_and_test:
    jobs:
      - unit_tests
