version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/openjdk:23.0.1  # Imagen base con Java
      - image: mysql:8.0            # Imagen de MySQL como servicio
      - image: selenium/standalone-chrome  # Imagen de Selenium con Chrome
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: calidad

    steps:
      - checkout  # Realiza el checkout del código fuente

      - run:
          name: Configurar base de datos
          command: |
            echo "Creando base de datos para pruebas..."
            mysql -h 127.0.0.1 -u root -proot -e "CREATE DATABASE calidad;"

      - run:
          name: Instalar cliente MySQL
          command: |
            sudo apt-get update
            sudo apt-get install -y mysql-client

      - run:
          name: Compilar proyecto y ejecutar pruebas específicas
          command: |
            mvn clean install -DskipTests  # Compila el proyecto sin ejecutar pruebas
            mvn test -Dtest=src.test.java.com.mayab.quality.functional.CRUDSeleniumTest  # Ejecutar prueba CRUDSeleniumTest
            mvn test -Dtest=src.test.java.com.mayab.quality.functional.SeleniumTest  # Ejecutar prueba SeleniumTest
            mvn test -Dtest=src.test.java.com.mayab.quality.integration.UserDAOTest  # Ejecutar prueba UserDAOTest
            mvn test -Dtest=src.test.java.com.mayab.quality.unittest.integration.UserDAOTest  # Ejecutar prueba UserDAOTest
            mvn test -Dtest=src.test.java.com.mayab.quality.unittest.service.UserDAOTest  # Ejecutar prueba UserDAOTest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
