version: 2.1

jobs:
  unit_tests:
    docker:
      - image: circleci/openjdk:11  # Imagen principal con OpenJDK 11
      - image: circleci/mysql:5.7   # Servicio de MySQL
        name: mysql
        environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: calidad2024
        command: --default-authentication-plugin=mysql_native_password
    steps:
      - checkout

      # Actualizar paquetes
      - run:
          name: Update package manager
          command: sudo apt-get update

      # Instalar cliente MySQL
      - run:
          name: Install MySQL Client
          command: sudo apt-get install -y default-mysql-client

      # Instalar Dockerize para esperar a que MySQL esté listo
      - run:
          name: Install Dockerize
          command: |
            wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz
            sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz
            rm dockerize-linux-amd64-v0.6.1.tar.gz

      # Esperar a que MySQL esté listo
      - run:
          name: Wait for MySQL
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m

      # Importar esquema SQL
      - run:
          name: Install MySQL and import schema
          command: |
            sudo apt update && sudo apt install -y default-mysql-client
            echo "Importing schema from src/resources/schema.sql..."
            mysql -h 127.0.0.1 -uroot -p123456 calidad2024 < src/resources/schema.sql
            echo "Checking tables in calidad2024..."
            mysql -h 127.0.0.1 -uroot -p123456 calidad2024 -e "SHOW TABLES;"
            echo "SELECT * FROM usuarios;" | mysql -h 127.0.0.1 -uroot -p123456 calidad2024
            echo "done"

      # Construir el proyecto sin ejecutar pruebas
      - run:
          name: Build the project
          command: mvn clean install -DskipTests

      # Ejecutar pruebas ignorando UserDAOTest y UserServiceTest
      - run:
          name: Run unit tests (excluding UserDAOTest and UserServiceTest)
          command: |
            mvn test -Dtest=UserDAOTest,UserServiceTest,CRUDSeleniumTest,LoginServiceTest

workflows:
  version: 2
  build_and_test:
    jobs:
      - unit_tests
