version: 2.1

jobs:
  unit_tests:
    docker:
      - image: circleci/openjdk:11  # Base image con OpenJDK 11
    steps:
      - checkout

      # Actualizar paquetes
      - run:
          name: Update package manager
          command: sudo apt-get update

      # Instalar Maven
      - run:
          name: Install Maven
          command: sudo apt-get install -y maven

      # Instalar Google Chrome
      - run:
          name: Install Google Chrome
          command: |
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable

      # Descargar y configurar ChromeDriver
      - run:
          name: Install ChromeDriver
          command: |
            CHROME_DRIVER_VERSION=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
            wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            sudo mv chromedriver /usr/local/bin/
            sudo chmod +x /usr/local/bin/chromedriver

      # Construir el proyecto sin ejecutar pruebas
      - run:
          name: Build the project
          command: mvn clean install -DskipTests

      # Ejecutar pruebas ignorando UserDAOTest y UserServiceTest
      - run:
          name: Run unit tests (excluding UserDAOTest and UserServiceTest)
          command: |
            mvn test -Dtest=!UserDAOTest,!UserServiceTest,CRUDSeleniumTest,SeleniumTest,LoginServiceTest

workflows:
  version: 2
  build_and_test:
    jobs:
      - unit_tests
