version: 2.1

jobs:
  build:
    working_directory: ~/circleci-java
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y maven
      - run:
          name: Build project
          command: mvn clean install

  test:
    working_directory: ~/circleci-java
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: Run tests with JUnit and DBUnit
          command: mvn test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
