version: 2.1

jobs:
  unit_tests:
    docker:
      - image: circleci/openjdk:11
      - image: circleci/mysql:5.7
        name: mysql
        environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: calidad2024
        command: --default-authentication-plugin=mysql_native_password
    steps:
      - checkout

      # Actualizar paquetes
      - run:
          name: Update package manager
          command: sudo apt-get update

      # Instalar cliente MySQL
      - run:
          name: Install MySQL Client
          command: sudo apt-get install -y default-mysql-client

      # Instalar Dockerize
      - run:
          name: Install Dockerize
          command: |
            wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz
            sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz
            rm dockerize-linux-amd64-v0.6.1.tar.gz

      # Esperar a que MySQL esté listo
      - run:
          name: Wait for MySQL
          command: dockerize -wait tcp://mysql:3306 -timeout 1m

      # Configurar base de datos con esquema SQL
      - run:
          name: Apply schema
          command: |
            echo "Applying schema..."
            mysql -h mysql -uroot -p123456 calidad2024 < src/resources/schema.sql
            echo "Schema applied successfully."

      # Verificar tablas en la base de datos
      - run:
          name: Verify MySQL Schema
          command: |
            echo "Checking database schema..."
            mysql -h mysql -uroot -p123456 calidad2024 -e "SHOW TABLES;"
            echo "Database schema verified."

      # Construir el proyecto sin ejecutar pruebas
      - run:
          name: Build the project
          command: mvn clean install -DskipTests

      # Ejecutar pruebas
      - run:
          name: Run integration tests
          command: mvn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - unit_tests
