version: 2.1

jobs:
  unit_tests:
    docker:
      - image: circleci/openjdk:11  # Imagen principal con OpenJDK 11
      - image: circleci/mysql:5.7   # Servicio de MySQL
        environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: calidad2024
    steps:
      - checkout

      # Actualizar paquetes
      - run:
          name: Update package manager
          command: sudo apt-get update

      # Instalar cliente MySQL desde el repositorio oficial
      - run:
          name: Install MySQL client
          command: |
            sudo apt-get update
            sudo apt-get install -y wget gnupg
            wget https://dev.mysql.com/get/mysql-apt-config_0.8.24-1_all.deb
            sudo dpkg -i mysql-apt-config_0.8.24-1_all.deb
            sudo apt-get update
            sudo apt-get install -y mysql-client
            rm mysql-apt-config_0.8.24-1_all.deb

      # Instalar Dockerize para esperar a que MySQL esté listo
      - run:
          name: Install Dockerize
          command: |
            wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz
            sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz
            rm dockerize-linux-amd64-v0.6.1.tar.gz

      # Esperar a que MySQL esté listo
      - run:
          name: Wait for MySQL
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m

      # Configurar base de datos con esquema SQL
      - run:
          name: Configure database schema
          command: |
            echo "Aplicando esquema de la base de datos desde .circleci/schema.sql..."
            mysql -h 127.0.0.1 -u root -proot calidad2024 < .circleci/schema.sql

      # Instalar Maven
      - run:
          name: Install Maven
          command: sudo apt-get install -y maven

      # Construir el proyecto sin ejecutar pruebas
      - run:
          name: Build the project
          command: mvn clean install -DskipTests

      # Ejecutar pruebas ignorando UserDAOTest y UserServiceTest
      - run:
          name: Run unit tests (excluding UserDAOTest and UserServiceTest)
          command: |
            mvn test -Dtest=!UserDAOTest,!UserServiceTest,CRUDSeleniumTest,SeleniumTest,LoginServiceTest

workflows:
  version: 2
  build_and_test:
    jobs:
      - unit_tests
