version: 2.1

jobs:
  unit_tests:
    docker:
      - image: circleci/openjdk:11  # Imagen principal con OpenJDK 11
      - image: circleci/mysql:5.7   # Servicio de MySQL
        environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: calidad2024
    steps:
      - checkout

      # Actualizar paquetes
      - run:
          name: Update package manager
          command: sudo apt-get update

      # Instalar certificados Java
      - run:
          name: Install ca-certificates-java
          command: sudo apt-get install -y ca-certificates-java

      # Instalar JDK predeterminado
      - run:
          name: Install Default JDK
          command: sudo apt-get install -y default-jdk

      # Instalar cliente MySQL usando default-mysql-client
      - run:
          name: Install MySQL Client
          command: |
            sudo apt-get install -y default-mysql-client

      # Instalar Dockerize para esperar a que MySQL esté listo
      - run:
          name: Install Dockerize
          command: |
            wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz
            sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz
            rm dockerize-linux-amd64-v0.6.1.tar.gz

      # Esperar a que MySQL esté listo
      - run:
          name: Wait for MySQL
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m

      # Configurar base de datos con esquema SQL
      - run:
          name: Configure database schema
          command: |
            echo "SOURCE src/resources/schema.sql;" | mysql -h 127.0.0.1 -u root -p123456 calidad2024

      # Construir el proyecto sin ejecutar pruebas
      - run:
          name: Build the project
          command: mvn clean install -DskipTests

      # Ejecutar pruebas ignorando UserDAOTest y UserServiceTest
      - run:
          name: Run unit tests (excluding UserDAOTest and UserServiceTest)
          command: |
            mvn test -Dtest=!UserDAOTest,!UserServiceTest,CRUDSeleniumTest,SeleniumTest,LoginServiceTest

workflows:
  version: 2
  build_and_test:
    jobs:
      - unit_tests
