version: 2.1

jobs:
  unit_tests:
    docker:
      - image: circleci/openjdk:11  # Base image con OpenJDK 11
    steps:
      - checkout

      # Actualizar paquetes y solucionar problemas de ca-certificates-java
      - run:
          name: Update package manager
          command: sudo apt-get update

      - run:
          name: Fix ca-certificates-java issue
          command: |
            sudo apt-get purge --auto-remove -y ca-certificates-java
            sudo apt-get install -y ca-certificates-java

      # Instalar Maven
      - run:
          name: Install Maven
          command: sudo apt-get install -y maven

      # Construir el proyecto
      - run:
          name: Build the project
          command: mvn clean install -DskipTests

      # Ejecutar pruebas ignorando UserDAOTest y UserServiceTest
      - run:
          name: Run unit tests (excluding UserDAOTest and UserServiceTest)
          command: |
            mvn test -Dtest=!UserDAOTest,!UserServiceTest,CRUDSeleniumTest,SeleniumTest,LoginServiceTest

workflows:
  version: 2
  build_and_test:
    jobs:
      - unit_tests
