version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/openjdk:23.0.1  # Imagen base con Java
      - image: selenium/standalone-chrome  # Imagen de Selenium con Chrome
      - image: mysql:8.0            # Imagen de MySQL como servicio
        environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: calidad

    steps:
      - checkout  # Realiza el checkout del código fuente

      # Instalar cliente MySQL
      - run:
          name: Instalar cliente MySQL
          command: |
            sudo apt-get update
            sudo apt-get install -y mysql-client

      # Configurar base de datos
      - run:
          name: Configurar base de datos
          command: |
            echo "Creando base de datos para pruebas..."
            mysql -h mysql -u root -proot -e "CREATE DATABASE calidad;"

      # Compilar el proyecto y ejecutar pruebas específicas
      - run:
          name: Compilar proyecto y ejecutar pruebas
          command: |
            mvn clean install -DskipTests  # Compila el proyecto sin ejecutar pruebas
            mvn test -Dtest=com.mayab.quality.functional.CRUDSeleniumTest,com.mayab.quality.functional.SeleniumTest,com.mayab.quality.integration.UserDAOTest,com.mayab.quality.unittest.integration.UserDAOTest,com.mayab.quality.unittest.service.UserDAOTest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
